version: "3"

services:
  territorial:
    build: ./api-territorial
    command: npm start
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/app/territorial
  transparencia:
    build: ./api-transparencia
    command: npm start
    ports:
      - "3031:3031"
    volumes:
      - .:/usr/app/transparencia
  saude:
    build: ./api-saude
    command: npm start
    ports:
      - "3032:3032"
    volumes:
      - .:/usr/app/saude
  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml