global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  static_configs:
  - targets: ['api-env_territorial_1:3030', 'api-env_transparencia_1:3031', 'api-env_saude_1:3032']